exclude: [README.md, _bin, run-jekyll.sh]

markdown: redcarpet
redcarpet:
  extensions: [ "tables" ]

gems:
  - jekyll-redirect-from

baseurl: /storm

issue_base_url: "https://issues.infn.it/browse/"
website_base_url: "http://italiangrid.github.io/storm"
repo_base_url: "https://github.com/italiangrid"

howto_path: "/documentation/how-to"

sysadmin_guide_version: 1.11.9
functional_description_version: 1.11.2
webdav_guide_version: 1.0.2
