exclude: [README.md, _bin, run-jekyll.sh]

emptyArray: []

kramdown:
  input: GFM
  hard_wrap: false
gems:
#  - jekyll-coffeescript
#  - jekyll-paginate
  - jekyll-redirect-from

baseurl: /storm
future: true

issue_base_url: "https://issues.infn.it/browse/"
website_base_url: "http://italiangrid.github.io/storm"
repo_base_url: "https://github.com/italiangrid"

howto_path: "/documentation/how-to"
releasenotes_path: "/release-notes"

latest_release: 1.11.12

sysadmin_guide_version: 1.11.12
functional_description_version: 1.11.2
webdav_guide_version: 1.0.2
